### PR TITLE
start algorithm save input in code api

### PR DESCRIPTION
**Pull request by golanha**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/nodejs-wrapper.hkube/28)

### CODE REVIEW

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/nodejs-wrapper.hkube/28)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @golanha and @yehiyam)

___
*[lib/algorunner.js, line 214 at r1](https://reviewable.io/reviews/kube-hpc/nodejs-wrapper.hkube/28#-MXRb0GID_EPCfcTOCjW:-MXRb0GID_EPCfcTOCjX:b-b22nzz) ([raw file](https://github.com/kube-hpc/nodejs-wrapper.hkube/blob/e9783311bfb17a47487be085b10843400a0786a7/lib/algorunner.js#L214)):*
> ```
> this._input;
> ```
You can do `return this._input?.jobId`
___
*[lib/codeApi/codeApi.js, line 82 at r1](https://reviewable.io/reviews/kube-hpc/nodejs-wrapper.hkube/28#-MXRa1H6COp6XmoS6JSm:-MXRa1H6COp6XmoS6JSn:b-rms97r) ([raw file](https://github.com/kube-hpc/nodejs-wrapper.hkube/blob/e9783311bfb17a47487be085b10843400a0786a7/lib/codeApi/codeApi.js#L82)):*
> ```
> startAlgorithm
> ```
This must be an async function.

**Review by golanha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/nodejs-wrapper.hkube/28)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @NassiHarel and @yehiyam)

___
*[lib/algorunner.js, line 214 at r1](https://reviewable.io/reviews/kube-hpc/nodejs-wrapper.hkube/28#-MXRb0GID_EPCfcTOCjW:-MXS6RA226STimCwOveJ:b-896fix) ([raw file](https://github.com/kube-hpc/nodejs-wrapper.hkube/blob/e9783311bfb17a47487be085b10843400a0786a7/lib/algorunner.js#L214)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> this._input;
> ```
You can do `return this._input?.jobId`
</blockquote></details>

Done.
___
*[lib/codeApi/codeApi.js, line 82 at r1](https://reviewable.io/reviews/kube-hpc/nodejs-wrapper.hkube/28#-MXRa1H6COp6XmoS6JSm:-MXS6QVV9oBLsN8u68BW:b-896fix) ([raw file](https://github.com/kube-hpc/nodejs-wrapper.hkube/blob/e9783311bfb17a47487be085b10843400a0786a7/lib/codeApi/codeApi.js#L82)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> startAlgorithm
> ```
This must be an async function.

</blockquote></details>

Done.

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/nodejs-wrapper.hkube/28)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @golanha and @yehiyam)

___
*[lib/codeApi/codeApi.js, line 82 at r1](https://reviewable.io/reviews/kube-hpc/nodejs-wrapper.hkube/28#-MXRa1H6COp6XmoS6JSm:-MXS7DCG6hzKTqOSdubu:b-r3s9w0) ([raw file](https://github.com/kube-hpc/nodejs-wrapper.hkube/blob/e9783311bfb17a47487be085b10843400a0786a7/lib/codeApi/codeApi.js#L82)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

No, it's still not async function....

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/nodejs-wrapper.hkube/28)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @golanha and @yehiyam)

___
*[lib/codeApi/codeApi.js, line 86 at r2](https://reviewable.io/reviews/kube-hpc/nodejs-wrapper.hkube/28#-MXVeH3sAoaFuz_9rwrK:-MXVeH3sAoaFuz_9rwrL:b-wou6jj) ([raw file](https://github.com/kube-hpc/nodejs-wrapper.hkube/blob/a798e62f7eef2f62ae11227e18279228d9a22e0a/lib/codeApi/codeApi.js#L86)):*
> ```JavaScript
>         const storage = {};
>         input.forEach((inp) => {
>             const taskId = uuid();
> ```

```
  await Promise.all(input.map(async (inp) => {
                const taskId = uuid();
                const { header, payload: encodedData } = this._dataAdapter.encodeHeaderPayload(inp);
                const storageInfo = this._dataAdapter.createStorageInfo({ jobId, taskId, encodedData });
                storage[taskId] = storageInfo;
                await this._dataAdapter.setData({ header, jobId, taskId, data: encodedData });
                return `$$${taskId}`;
}));
```

**Review by golanha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/nodejs-wrapper.hkube/28)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @NassiHarel and @yehiyam)

___
*[lib/codeApi/codeApi.js, line 82 at r1](https://reviewable.io/reviews/kube-hpc/nodejs-wrapper.hkube/28#-MXRa1H6COp6XmoS6JSm:-MXVtVTg5hbTj8SGgdME:b-896fix) ([raw file](https://github.com/kube-hpc/nodejs-wrapper.hkube/blob/e9783311bfb17a47487be085b10843400a0786a7/lib/codeApi/codeApi.js#L82)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

No, it's still not async function....
</blockquote></details>

Done.
___
*[lib/codeApi/codeApi.js, line 86 at r2](https://reviewable.io/reviews/kube-hpc/nodejs-wrapper.hkube/28#-MXVeH3sAoaFuz_9rwrK:-MXVtVvA2Ha6pRgOIKZZ:b-896fix) ([raw file](https://github.com/kube-hpc/nodejs-wrapper.hkube/blob/a798e62f7eef2f62ae11227e18279228d9a22e0a/lib/codeApi/codeApi.js#L86)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

  await Promise.all(input.map(async (inp) => {
                const taskId = uuid();
                const { header, payload: encodedData } = this._dataAdapter.encodeHeaderPayload(inp);
                const storageInfo = this._dataAdapter.createStorageInfo({ jobId, taskId, encodedData });
                storage[taskId] = storageInfo;
                await this._dataAdapter.setData({ header, jobId, taskId, data: encodedData });
                return `$$${taskId}`;
}));


</blockquote></details>

Done.

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/nodejs-wrapper.hkube/28)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @golanha and @yehiyam)

___
*[lib/codeApi/codeApi.js, line 82 at r3](https://reviewable.io/reviews/kube-hpc/nodejs-wrapper.hkube/28#-MXVwcEu-aWwLNQEHXWW:-MXVwcEu-aWwLNQEHXWX:b-aqq3vu) ([raw file](https://github.com/kube-hpc/nodejs-wrapper.hkube/blob/8b51a5b6157dc940c5d4691cb06c087d1e2a6998/lib/codeApi/codeApi.js#L82)):*
> ```
> async startAlgorithm
> ```
Do we have a unit test for this function?

**Review by golanha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/nodejs-wrapper.hkube/28)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @NassiHarel and @yehiyam)

___
*[lib/codeApi/codeApi.js, line 82 at r3](https://reviewable.io/reviews/kube-hpc/nodejs-wrapper.hkube/28#-MXVwcEu-aWwLNQEHXWW:-MXW_QtDEp1N8Hbu2lx_:bl4xia9) ([raw file](https://github.com/kube-hpc/nodejs-wrapper.hkube/blob/8b51a5b6157dc940c5d4691cb06c087d1e2a6998/lib/codeApi/codeApi.js#L82)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> async startAlgorithm
> ```
Do we have a unit test for this function?
</blockquote></details>

Done.
Yes, I added check that the new parameters are built.

**Review by NassiHarel — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/nodejs-wrapper.hkube/28#-:-MXWoUzE6rtqMC1nlCvn:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yehiyam)

**Pull request merged**
