### PR TITLE
redirect logs for debug

### PR DESCRIPTION
**Pull request by golanha**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/nodejs-wrapper.hkube/37)

### CODE REVIEW

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/nodejs-wrapper.hkube/37)* status: all files reviewed, 4 unresolved discussions (waiting on @golanha)

___
*[lib/algorunner.js, line 23 at r1](https://reviewable.io/reviews/kube-hpc/nodejs-wrapper.hkube/37#-MfbL6PFDLivpcjuy7b0:-MfbL6PFDLivpcjuy7b1:b-djnkst) ([raw file](https://github.com/kube-hpc/nodejs-wrapper.hkube/blob/9a654a726707785baf0bb3d30335aa77976dc2e9/lib/algorunner.js#L23)):*
> ```JavaScript
>         this._startSpan = undefined;
>         this._hkubeApi = null;
>         this._originalStdoutWrite = process.stdout.write;
> ```

what about stderr?
___
*[lib/algorunner.js, line 29 at r1](https://reviewable.io/reviews/kube-hpc/nodejs-wrapper.hkube/37#-MfbEZstBsi1kwvGDtBH:-MfbEZstBsi1kwvGDtBI:b5sa0yd) ([raw file](https://github.com/kube-hpc/nodejs-wrapper.hkube/blob/9a654a726707785baf0bb3d30335aa77976dc2e9/lib/algorunner.js#L29)):*
> ```JavaScript
>     }
> 
>     reportStdoutForDebug() {
> ```

why not pass it in the constructor, or like in the python wrapper pass it as options to `loadAlgorithm`
___
*[lib/algorunner.js, line 248 at r1](https://reviewable.io/reviews/kube-hpc/nodejs-wrapper.hkube/37#-MfbMcUT3GUEDdcSKrc9:-MfbMcUT3GUEDdcSKrcA:b-rv66k2) ([raw file](https://github.com/kube-hpc/nodejs-wrapper.hkube/blob/9a654a726707785baf0bb3d30335aa77976dc2e9/lib/algorunner.js#L248)):*
> ```JavaScript
>     async _redirect() {
>         process.stdout.write = (printData) => {
>             const data = printData.split('\n');
> ```

perhaps trim the last `\n` in `printData` before splitting. Otherwise you will get an extra line
___
*[lib/algorunner.js, line 250 at r1](https://reviewable.io/reviews/kube-hpc/nodejs-wrapper.hkube/37#-MfbKmFBBHzs0wQoGvE4:-MfbKmFBBHzs0wQoGvE5:b-juitim) ([raw file](https://github.com/kube-hpc/nodejs-wrapper.hkube/blob/9a654a726707785baf0bb3d30335aa77976dc2e9/lib/algorunner.js#L250)):*
> ```JavaScript
>             const data = printData.split('\n');
>             this._sendCommand({ command: messages.outgoing.logData, data });
>             this._originalStdoutWrite(printData);
> ```

Did you check if the original log works? I think you need to either bind it to process.stdout or call it with apply

**Review by yehiyam — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/nodejs-wrapper.hkube/37)* status: all files reviewed, 5 unresolved discussions (waiting on @golanha)

*[a discussion](https://reviewable.io/reviews/kube-hpc/nodejs-wrapper.hkube/37#-MfbXS325lNGMRTFEtCd:-MfbXS325lNGMRTFEtCe:b-8nr9fg) (no related file):*
you need to ignore logging logData messages. Same as in python
`if (message.get('command') != messages.outgoing.logData):`

---

**Review by golanha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/nodejs-wrapper.hkube/37)* status: 1 of 4 files reviewed, 5 unresolved discussions (waiting on @yehiyam)

*[a discussion](https://reviewable.io/reviews/kube-hpc/nodejs-wrapper.hkube/37#-MfbXS325lNGMRTFEtCd:-MfbiPVH77N_Co9CCpmQ:b-896fix) (no related file):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

you need to ignore logging logData messages. Same as in python
`if (message.get('command') != messages.outgoing.logData):`
</blockquote></details>

Done.

---
___
*[lib/algorunner.js, line 23 at r1](https://reviewable.io/reviews/kube-hpc/nodejs-wrapper.hkube/37#-MfbL6PFDLivpcjuy7b0:-MfbjfsD0sM_9ZBHokhB:b-896fix) ([raw file](https://github.com/kube-hpc/nodejs-wrapper.hkube/blob/9a654a726707785baf0bb3d30335aa77976dc2e9/lib/algorunner.js#L23)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

what about stderr?
</blockquote></details>

Done.
___
*[lib/algorunner.js, line 29 at r1](https://reviewable.io/reviews/kube-hpc/nodejs-wrapper.hkube/37#-MfbEZstBsi1kwvGDtBH:-MfbkzoY6QZbZcPHsXNo:b-896fix) ([raw file](https://github.com/kube-hpc/nodejs-wrapper.hkube/blob/9a654a726707785baf0bb3d30335aa77976dc2e9/lib/algorunner.js#L29)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

why not pass it in the constructor, or like in the python wrapper pass it as options to `loadAlgorithm`
</blockquote></details>

Done.
___
*[lib/algorunner.js, line 248 at r1](https://reviewable.io/reviews/kube-hpc/nodejs-wrapper.hkube/37#-MfbMcUT3GUEDdcSKrc9:-MfboFDoCX76i6WhGzcy:b-896fix) ([raw file](https://github.com/kube-hpc/nodejs-wrapper.hkube/blob/9a654a726707785baf0bb3d30335aa77976dc2e9/lib/algorunner.js#L248)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

perhaps trim the last `\n` in `printData` before splitting. Otherwise you will get an extra line
</blockquote></details>

Done.
___
*[lib/algorunner.js, line 250 at r1](https://reviewable.io/reviews/kube-hpc/nodejs-wrapper.hkube/37#-MfbKmFBBHzs0wQoGvE4:-MfboPlN8IRmCn0bu1Gu:b-g1r3v) ([raw file](https://github.com/kube-hpc/nodejs-wrapper.hkube/blob/9a654a726707785baf0bb3d30335aa77976dc2e9/lib/algorunner.js#L250)):*
> rocess.stdout 
Yes, it wroks

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/nodejs-wrapper.hkube/37)* status: all files reviewed, 3 unresolved discussions (waiting on @golanha)

___
*[lib/algorunner.js, line 23 at r1](https://reviewable.io/reviews/kube-hpc/nodejs-wrapper.hkube/37#-MfbL6PFDLivpcjuy7b0:-Mfc7Aye82APk9DBls2E:b-jpcdi5) ([raw file](https://github.com/kube-hpc/nodejs-wrapper.hkube/blob/9a654a726707785baf0bb3d30335aa77976dc2e9/lib/algorunner.js#L23)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

why not put the logic in a util file? it will keep this file cleaner. Maybe do it like the python-wrapper? raise an event to send through the socket
___
*[lib/algorunner.js, line 250 at r1](https://reviewable.io/reviews/kube-hpc/nodejs-wrapper.hkube/37#-MfbKmFBBHzs0wQoGvE4:-Mfc7XhkBHAlGhfedopE:b-bejfia) ([raw file](https://github.com/kube-hpc/nodejs-wrapper.hkube/blob/9a654a726707785baf0bb3d30335aa77976dc2e9/lib/algorunner.js#L250)):*
<details><summary><i>Previously, golanha (Golan Hallel) wrote…</i></summary><blockquote>

> rocess.stdout 
Yes, it wroks
</blockquote></details>

When I tested it it didn't work
___
*[lib/algorunner.js, line 80 at r2](https://reviewable.io/reviews/kube-hpc/nodejs-wrapper.hkube/37#-Mfc6GisBvdY95LKzOJY:-Mfc6GisBvdY95LKzOJZ:b-dbjz50) ([raw file](https://github.com/kube-hpc/nodejs-wrapper.hkube/blob/3840d7f80bc225184a38c1e5d6c16169252b4b0d/lib/algorunner.js#L80)):*
> ```JavaScript
>             const algorithm = Algorunner.requireAlgorithm(options);
>             this._loadAlgorithm(algorithm);
>             this._logDebug = options.logs;
> ```

This is redundant because it is set in this._loadAlgorithm

**Review by golanha — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/nodejs-wrapper.hkube/37)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @yehiyam)

___
*[lib/algorunner.js, line 23 at r1](https://reviewable.io/reviews/kube-hpc/nodejs-wrapper.hkube/37#-MfbL6PFDLivpcjuy7b0:-Mfcd5NcAxDK8mezOWKo:b-896fix) ([raw file](https://github.com/kube-hpc/nodejs-wrapper.hkube/blob/9a654a726707785baf0bb3d30335aa77976dc2e9/lib/algorunner.js#L23)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

why not put the logic in a util file? it will keep this file cleaner. Maybe do it like the python-wrapper? raise an event to send through the socket
</blockquote></details>

Done.
___
*[lib/algorunner.js, line 250 at r1](https://reviewable.io/reviews/kube-hpc/nodejs-wrapper.hkube/37#-MfbKmFBBHzs0wQoGvE4:-MfcdHbC0ikfR4fDecbq:b-896fix) ([raw file](https://github.com/kube-hpc/nodejs-wrapper.hkube/blob/9a654a726707785baf0bb3d30335aa77976dc2e9/lib/algorunner.js#L250)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

When I tested it it didn't work
</blockquote></details>

Done.
___
*[lib/algorunner.js, line 80 at r2](https://reviewable.io/reviews/kube-hpc/nodejs-wrapper.hkube/37#-Mfc6GisBvdY95LKzOJY:-MfcdGF24lsMnmIEP21G:b-896fix) ([raw file](https://github.com/kube-hpc/nodejs-wrapper.hkube/blob/3840d7f80bc225184a38c1e5d6c16169252b4b0d/lib/algorunner.js#L80)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

This is redundant because it is set in this._loadAlgorithm 
</blockquote></details>

Done.

**Review by yehiyam — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/nodejs-wrapper.hkube/37)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @golanha)

**Review by yehiyam — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/kube-hpc/nodejs-wrapper.hkube/37#-:-Mfg1fN51GgKN8ZB65UV:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @golanha)

**Pull request merged**
