### PR TITLE
feat: apply all changes

### PR DESCRIPTION
**Pull request by NassiHarel**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/nodejs-wrapper.hkube/15)

### CODE REVIEW

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 8 of 9 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/nodejs-wrapper.hkube/15)* status: all files reviewed, 3 unresolved discussions (waiting on @golanha and @NassiHarel)

___
*[lib/algorunner.js, line 137 at r2](https://reviewable.io/reviews/kube-hpc/nodejs-wrapper.hkube/15#-MHvMNUA7Gw-0PT6wCK3:-MHvMNUB27IGXpRGPj9i:b3gplfp) ([raw file](https://github.com/kube-hpc/nodejs-wrapper.hkube/blob/28b19c7f208fda06c35bf0ab748b3d45968de0f9/lib/algorunner.js#L137)):*
> ```JavaScript
>             const isServing = this._dataServer.isServing();
>             if (isServing) {
>                 this._sendCommand({ command: messages.outgoing.servingStatus, data: true });
> ```

can `this._sendCommand` fail and throw? 
___
*[lib/algorunner.js, line 203 at r2](https://reviewable.io/reviews/kube-hpc/nodejs-wrapper.hkube/15#-MHvMZdg5DMYxzjv1vvZ:-MHvMZdg5DMYxzjv1vv_:b-9ajijg) ([raw file](https://github.com/kube-hpc/nodejs-wrapper.hkube/blob/28b19c7f208fda06c35bf0ab748b3d45968de0f9/lib/algorunner.js#L203)):*
> ```JavaScript
> 
>     async _handleResponseV2(algorithmData, jobId, taskId, nodeName, info) {
>         const { header, payload: encodedData } = dataAdapter._encoding.encodeHeaderPayload(algorithmData);
> ```

why _? if this is public remove it
___
*[lib/algorunner.js, line 215 at r2](https://reviewable.io/reviews/kube-hpc/nodejs-wrapper.hkube/15#-MHvP90r-4KTX2jQVe8t:-MHvP90r-4KTX2jQVe8u:bqct2w3) ([raw file](https://github.com/kube-hpc/nodejs-wrapper.hkube/blob/28b19c7f208fda06c35bf0ab748b3d45968de0f9/lib/algorunner.js#L215)):*
> ```JavaScript
>         else {
>             await dataAdapter.setData({ jobId, taskId, header, data: encodedData });
>             this._sendCommand({ command: messages.outgoing.storing, data: { discovery: this._discovery, taskId, ...storageInfo } });
> ```

In python we do not set discovery when there is no cache

**Review by NassiHarel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/nodejs-wrapper.hkube/15)* status: 8 of 9 files reviewed, 3 unresolved discussions (waiting on @golanha and @yehiyam)

___
*[lib/algorunner.js, line 137 at r2](https://reviewable.io/reviews/kube-hpc/nodejs-wrapper.hkube/15#-MHvMNUA7Gw-0PT6wCK3:-MHyyXJp6D8caYp9fsG5:b-896fix) ([raw file](https://github.com/kube-hpc/nodejs-wrapper.hkube/blob/28b19c7f208fda06c35bf0ab748b3d45968de0f9/lib/algorunner.js#L137)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

can `this._sendCommand` fail and throw? 
</blockquote></details>

Done.
___
*[lib/algorunner.js, line 203 at r2](https://reviewable.io/reviews/kube-hpc/nodejs-wrapper.hkube/15#-MHvMZdg5DMYxzjv1vvZ:-MHyzjPP9BvymdHGN91K:b-896fix) ([raw file](https://github.com/kube-hpc/nodejs-wrapper.hkube/blob/28b19c7f208fda06c35bf0ab748b3d45968de0f9/lib/algorunner.js#L203)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

why _? if this is public remove it
</blockquote></details>

Done.
___
*[lib/algorunner.js, line 215 at r2](https://reviewable.io/reviews/kube-hpc/nodejs-wrapper.hkube/15#-MHvP90r-4KTX2jQVe8t:-MHyzkiw8B2AHitdF-0a:b-896fix) ([raw file](https://github.com/kube-hpc/nodejs-wrapper.hkube/blob/28b19c7f208fda06c35bf0ab748b3d45968de0f9/lib/algorunner.js#L215)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

In python we do not set discovery when there is no cache
</blockquote></details>

Done.

**Review by yehiyam — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/nodejs-wrapper.hkube/15)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @golanha)

**Review by golanha — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/nodejs-wrapper.hkube/15)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @golanha)

**Review by yehiyam — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/nodejs-wrapper.hkube/15#-:-MIOJsxf0sRRtfaOTBd2:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
